### ISSUE TITLE
Upgrade of volumio breaks NanoSound (no more remote, partial OLED)

### ISSUE THREAD

**Issue by arthurlutz** [nanomesher/Nanomesher_NanoSound#5] opened 2019-08-24 16:40 UTC
After upgrading volumio to 2.599 (August 2nd) LIRC part of nanosound breaks (no more control).

Disable and enabling the plugin and watching the logs I find : 

```
2019-08-24T16:36:30.654Z - info: Enabling plugin nanosound
2019-08-24T16:36:30.657Z - info: Loading plugin "nanosound"...
2019-08-24T16:36:30.658Z - info: Starting NanoSound Plug-in
2019-08-24T16:36:30.659Z - info: Applying required configuration parameters for plugin nanosound
2019-08-24T16:36:30.663Z - info: 1
2019-08-24T16:36:30.664Z - info: 2
2019-08-24T16:36:30.665Z - info: Starting NanoSound
2019-08-24T16:36:30.667Z - info: PLUGIN START: nanosound
2019-08-24T16:36:30.667Z - info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
2019-08-24T16:36:30.840Z - info: NanoSound - Creating button triggers
2019-08-24T16:36:30.841Z - info: playPause on pin 13
2019-08-24T16:36:30.905Z - info: volumeUp on pin 10
2019-08-24T16:36:30.965Z - info: volumeDown on pin 9
2019-08-24T16:36:31.023Z - info: previous on pin 11
2019-08-24T16:36:31.073Z - info: next on pin 12
2019-08-24T16:36:31.121Z - info: shutdown on pin 4
2019-08-24T16:36:31.216Z - info: Done.
2019-08-24T16:36:31.237Z - info: Error enabling lirc-rpi overlay: Error: Command failed: /usr/bin/sudo /usr/bin/dtoverlay lirc-rpi gpio_in_pin=17
* Failed to apply overlay '2_lirc-rpi' (kernel)

2019-08-24T16:36:31.355Z - info: NanoSound OLED daemon started
2019-08-24T16:36:32.442Z - info: NanoSound lirc correctly started
2019-08-24T16:36:32.645Z - info: lirc correctly started

```

Looking into it.

**Comment by arthurlutz** [comment] 2019-08-24 16:53
This might be a problem related to the new kernel. `lirc-rpi` might be replaced by `gpi-ir` https://www.raspberrypi.org/forums/viewtopic.php?t=236240

```
/usr/bin/dtoverlay gpio-ir gpio_pin=17
```

seems to work. Produces the following in syslog : 

```
[681096.223178] rc rc0: gpio_ir_recv as /devices/platform/ir-receiver@19/rc/rc0
[681096.223440] input: gpio_ir_recv as /devices/platform/ir-receiver@19/rc/rc0/input0
[681096.223712] rc rc0: lirc_dev: driver gpio_ir_recv registered at minor = 0, raw IR receiver, no transmitter
[681096.777966] input: lircd as /devices/virtual/input/input1
[681098.587480] input: lircd as /devices/virtual/input/input2
[681133.770763] input: lircd as /devices/virtual/input/input3
[1714113.806490] input: lircd as /devices/virtual/input/input4
[1714482.694527] input: lircd as /devices/virtual/input/input5
[1714871.108491] Registered IR keymap rc-rc6-mce
[1714871.109182] rc rc1: gpio_ir_recv as /devices/platform/ir-receiver@11/rc/rc1
[1714871.109810] input: gpio_ir_recv as /devices/platform/ir-receiver@11/rc/rc1/input6
[1714871.110904] rc rc1: lirc_dev: driver gpio_ir_recv registered at minor = 1, raw IR receiver, no transmitter
[1714871.313293] input: lircd as /devices/virtual/input/input7
[1714881.897907] rc rc1: two consecutive events of type space
```

still not working ,but this might be because I seem to have lost my lirc configuration (not sure yet)

**Comment by arthurlutz** [comment] 2019-08-25 13:08
Here is an example of the code that does both dtoverlay : https://github.com/volumio/volumio-plugins/blob/master/plugins/accessory/ir_controller/index.js#L229-L257

**Comment by WarmChocolateCake** [comment] 2019-09-20 17:58
Just upgraded to 2.609 and this is still an issue.

Although, a brief look at my notes from [last time](https://github.com/volumio/volumio-plugins/issues/342), doesn't appear to magically fix this, this time... but I need to check again (more slowly / carefully)

Anyway, @nanomesher, this problem still appears to be a problem.

**Comment by nanomesher** [comment] 2019-09-21 14:12
hi all,

This is actually an issue caused by kernel 4.19 upgrade since volumio 2.599.

We have done a permanent fix with a new implementation and [awaiting PR to be merged](https://github.com/volumio/volumio-plugins/pull/354)

Before it is merged and deployed to volumio repo, you can install it manually [via method 3 
](https://nanomesher.com/support/nanosound-support/)

Moverover, with this implementation you can [adapt your own remote
](https://nanomesher.com/adapting-your-own-infrared-remote-with-nanosound/)

**Closed** 2019-09-21 14:13 UTC
